### ISSUE TITLE
Integrated broken after update on Mac OS X 26.3

### ISSUE THREAD

**Issue by eromang** [polyipseity/obsidian-terminal#119]
I updated this morning the terminal obsidian plug-in.

When I start the terminal in integrated mode I have now the following error:

Traceback (most recent call last):
                                    File "<string>", line 20, in <module>
                                                                         ImportError: cannot import name 'Self' from 'typing' (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/typing.py)

Best Regards

**Comment by janah01** [comment]
A fix has been introduced in PR #107 and is currently awaiting review.
In the meantime, my recommended workaround is to install Python 3.11 or higher on your machine. Once installed, add its path to the integrated terminal profile in the plugin settings and verify that it resolves correctly.

**Comment by polyipseity** [comment]
Fixed in the latest version v3.23.0. See #107.
