### PR TITLE
fix(python): use Python 3.9-compatible type annotations in unix_pseudoterminal.py

### PR DESCRIPTION
**Pull request by janah01**
## Summary

`src/terminal/unix_pseudoterminal.py` uses `from typing import Self` (Python 3.11+) and
`type[BaseException] | None` union syntax (Python 3.10+). The plugin runs this script on
whatever system Python the user has. On macOS, the Command Line Tools default is Python 3.9,
causing an `ImportError` at startup that prevents the terminal from launching.

This PR replaces the incompatible type annotations with equivalents that work on Python 3.9+.

---

### Error

```text
Traceback (most recent call last):
  File "<string>", line 20, in <module>
ImportError: cannot import name 'Self' from 'typing'
(/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/typing.py)
```

### Root cause

| Syntax | Requires | Source |
|--------|----------|--------|
| `from typing import Self` | Python 3.11 (PEP 673) | Line 20 |
| `type[BaseException] \| None` | Python 3.10 (PEP 604) | Line 70 |

### Introduced in

Commit (https://github.com/polyipseity/obsidian-terminal/commit/ab83e5373edb4ecd58e0c7cba8ddee221a86da0f `[refactor(terminal): selector handler context managers for unix PTY]`,
Feb 17 2026) refactored the Python file and introduced both incompatible constructs.

---

## Version check mismatch

The plugin settings UI says **"Recommend 3.10.0 or up"** and the version check shows
`Python: 3.9.6 (unsatisfied: >=3.10.0)`. However, the actual code requires **Python 3.11**
because `typing.Self` was added in PEP 673 (Python 3.11). This means:

- A user who installs Python 3.10 specifically because the UI told them to **will still crash**.
  Personally tested on a fresh Homebrew Python 3.10 installation:
  ```text
  Traceback (most recent call last):
    File "<string>", line 20, in <module>
  ImportError: cannot import name 'Self' from 'typing'
  (/opt/homebrew/Cellar/python@3.10/3.10.19_3/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py)
  ```
- The version check gives a false sense of what's needed

---

## Verified test results

Tested on real Python installations (macOS, Feb 28 2026):

### `from typing import Self` (the crash)

| Python version | Source | Result |
|---|---|---|
| 3.9.6 | macOS CLT (`/usr/bin/python3`) | **ImportError** — CRASH |
| 3.10.19 | Homebrew (`/opt/homebrew/bin/python3.10`) | **ImportError** — CRASH |
| 3.14.3 | Homebrew (`/opt/homebrew/bin/python3.14`) | OK |

### `type[BaseException] | None` (secondary issue)

| Python version | Source | Result |
|---|---|---|
| 3.9.6 | macOS CLT | **TypeError** — CRASH |
| 3.10.19 | Homebrew | OK |
| 3.14.3 | Homebrew | OK |

### Full plugin script (`unix_pseudoterminal.py`)

| Python version | Current main | With this fix |
|---|---|---|
| 3.9.6 (macOS CLT) | **ImportError at line 20** | Works |
| 3.10.19 (Homebrew) | **ImportError at line 20** | Works |
| 3.14.3 (Homebrew) | Works | Works |

### Verified in Obsidian

- Set Python executable to `/opt/homebrew/bin/python3.10` in plugin settings — **crashes**
- Set Python executable to `/opt/homebrew/bin/python3.14` — works
- Default `python3` (resolves to Homebrew 3.14 in terminal, CLT 3.9 from Finder) — depends on launch method

---

## macOS Python landscape

1. **macOS does not ship Python 3 pre-installed.** `/usr/bin/python3` is a shim that prompts
   Xcode Command Line Tools (CLT) installation when first invoked.

2. **CLT Python is 3.9.6** across Ventura (13), Sonoma (14), Sequoia (15), and Tahoe (26). Apple has
   kept this version locked for stability. It has not been updated to 3.10+.

3. **Finder/Spotlight launches bypass shell config.** Obsidian launched from Finder does NOT
   load `~/.zshrc` or `~/.bash_profile`. It inherits the system PATH, so `python3` resolves
   to `/usr/bin/python3` (CLT 3.9.6), not any Homebrew or pyenv installation.

4. **The CLT install path is the path of least resistance** for non-developer macOS users.
   When they first run `python3`, macOS prompts a GUI dialog to install CLT. After clicking
   "Install", they get Python 3.9.6.

---

## Why `from __future__ import annotations` alone is not enough

`from __future__ import annotations` makes type hints lazy (string-based), which fixes
the `type[X] | None` syntax at annotation sites. However, it does NOT fix the `ImportError`
because `from typing import Self` is a real import statement that executes at module load
time regardless of `__future__` annotations. The name `Self` simply does not exist in
Python 3.9 or 3.10's `typing` module.

Both changes are needed:
1. `from __future__ import annotations` — fixes `type[X] | None` on Python 3.9
2. Remove `from typing import Self` — fixes the `ImportError` on Python 3.9 and 3.10

### The fix

The crash happens because `from typing import Self` is a real import that runs at module load time — it's not a type annotation, so `from __future__ import annotations` alone can't prevent the `ImportError`.

I removed the `Self` import entirely and replaced the `-> Self` return hint with the explicit class name (`-> _SelectorHandler`) as a forward reference. I also added `from __future__ import annotations` to lazily evaluate the `type[X] | None` union syntax, which otherwise breaks on Python 3.9.

Straightforward 3-line change, zero behavioral impact. pyright and ruff continue to pass without issue.

### CI checks

All pass — ESLint, Prettier, Markdownlint, ruff, pyright, pytest (5 passed), Vitest (100 tests), clean build. Manually verified on Python 3.9.6 (macOS CLT), 3.10.19 (Homebrew), and 3.14.3 (Homebrew).

### Note

The plugin version check says `>=3.10.0` but the code requires `>=3.11` due to `typing.Self`. You may want to either:
- Accept this fix to restore compatibility with Python 3.9+ (zero maintenance burden)
- Update the version check to `>=3.11` to match the actual requirement
- Both

### CODE REVIEW

**Comment by polyipseity** [comment]
Mightn as well also change the minimum Python version to 3.9 (I already committed the changes).
